### ISSUE TITLE
Use docker compose for service deployment

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/signroom#758]
On service download in the root folder two new files should be added:
* docker-compose.yaml
  ```yaml
  services:
    # this define caddy server, everythhing is handled by the Caddyfile
    caddy:
      container_name: caddy
      image: caddy:alpine
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
        - "443:443/udp"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./site:/srv
        - caddy_data:/data
        - caddy_config:/config
    
    # for each downloaded microservice add the following
    # part by substituting
    # {{ MS_NAME }} -> microservice folder name
    # {{ MS_URL }} -> microservice baseUrl 
    # {{ MS_TYPE }} -> microservice type (authz_server, credential_issuer, relying_party)
    {{ MS_NAME }}:
      container_name: {{ MS_NAME }}
      image: ghcr.io/forkbombeu/didroom_microservices:latest
      environment:
        MS_URL: {{ MS_URL }}
        MS_NAME: {{ MS_NAME }}
        ZENCODE_DIR: /app/{{ MS_TYPE }}
        PUBLIC_DIR: /app/public/{{ MS_TYPE }}
      volumes:
        - type: bind
          source: ./{{ MS_NAME }}/{{ MS_TYPE }}
          target: /app/{{ MS_TYPE }}
        - type: bind
          source: ./{{ MS_NAME }}/public
          target: /app/public

  volumes:
    caddy_data:
    caddy_config:
  ```
* Caddyfile
  ```caddy
  # for each downloaded microservice add the following
  # part by substituting
  # {{ MS_NAME }} -> microservice folder name
  # {{ MS_URL }} -> microservice baseUrl
  # {{ MS_TYPE }} -> microservice type (authz_server, credential_issuer, relying_party)
  {{ MS_URL }} {
    handle_path /{{ MS_TYPE }}/* {
      uri strip_prefix /{{ MS_TYPE }}
      reverse_proxy {{ MS_NAME }}:3000
    }
    reverse_proxy {{ MS_NAME }}:3000
  }}
  ```
  

If everything goes well the final user should only do
```sh
unzip microservices.zip
docker compose up #-d for dateched mode
```
and all services should be up and running.
Moreover the UP_PORT is no more needed 🎉 

# Problem

This solution does not work if something else like ngnix or caddy are already present on the server since when caddy will try to bind to port 80/443 it will find them already busy and will return an error.

This implies that also signle services can not be downloaded alone, but all the services that run on the same machine should be downloaded together. 

I hope this limitation is there only beacuse I'm not so familiar with docker compose 🧐
